### ISSUE TITLE
Issue 11: Basic User Registration and Login

### ISSUE THREAD

**Issue by AVTpepper** [AVTpepper/onestop-artist-shop#22]
**User Story:** As a visitor, I can create an account and log in, so that I can access exclusive features, such as saving my shopping cart and viewing my order history.

## Acceptance Criteria:

- Users should be able to register with their email address, a username, a password, and other necessary details.
- Users should be able to log in with their email address / username, and password.
- The login and registration process should be secure and include validation checks.

## Tasks:

- [x]  Design the user registration and login forms.
- [x]  Implement the forms in HTML and CSS.
- [x]  Implement backend functionality for user registration and login (use the backend tasks from Issue 8).
- [x]  Ensure security and validation checks during registration and login.
