### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by AVTpepper** [AVTpepper/onestop-artist-shop#30]
**User Story:**
As a user, I want to be able to register on the platform so that I can participate in artwork bidding or as a teacher, upload artworks.

**Acceptance Criteria:**
- [ ] A "Register" option is available on the home page.
- [ ] Clicking "Register" opens up a form asking for username, password, email, and whether the user is a teacher or not.
- [ ] After successful registration, the user is redirected to the login page.

**Tasks:**
- [ ] Create a User model in Django.
- [ ] Design a registration form using Django Crispy Forms.
- [ ] Implement form validation for user inputs.
- [ ] Create a registration view in Django to handle form submission and record creation in the database.
- [ ] Design a registration page in Bootstrap.
